apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.1.3
  image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
  nodeSets:

  - name: master-data-nodes
    count: 3
    config:
      node.roles: ["master","data","ingest","ml"]
    podTemplate:
      spec:
        volumes:
          - name: elasticsearch-data         
            emptyDir: {}
        containers:
          - name: elasticsearch
            env:
            - name: ES_Java_OPTS
              value: -Xms8g -Xmx8g
            resources:
              requests:
               memory: 2Gi
               cpu: 2
              limits:
               memory: 2Gi
            readinessProbe:
              exec:
                command:
                - bash
                - -c
                - /mnt/elastic-internal/scripts/readiness-probe-script.sh
                - sysctl -w vm.max_map_count=262144
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 12
              successThreshold: 1
              timeoutSeconds: 15
        volumes:
        - name: elasticsearch-data
          emptyDir: {}         
                